# Java Installation
- name: add repo for java 8, maven3
  apt_repository: repo='{{ item }}' state=present
  with_items:
    - ppa:andrei-pozolotin/maven3
    - ppa:webupd8team/java
  become: yes

- name: set licence selected
  shell: /bin/echo debconf shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
  become: yes

- name: set licence seen
  shell: /bin/echo debconf shared/accepted-oracle-license-v1-1 seen true | /usr/bin/debconf-set-selections
  become: yes
# Update cache
- name: Update APT package cache
  apt: update_cache=yes
  become: yes
  register: updated
# Install Packages
- name: Install Java8, Git, Maven
  apt: name={{ item }} state=latest update-cache=yes force=yes
  with_items:
    - oracle-java8-installer
    - git
    - maven3
  when: updated.changed
  become: yes
